export enum IntentType {
  CompleteGame = "CompleteGame",
  StartGame = "StartGame",
  PauseGame = "PauseGame",
  DropGame = "DropGame",
  LaunchGame = "LaunchGame",
  RateGame = "RateGame",
  ReviewGame = "ReviewGame",
  DeleteReview = "DeleteReview",
  FindGame = "FindGame",
  RecommendGame = "RecommendGame",
  CompareGames = "CompareGames",
  OrganizeLibrary = "OrganizeLibrary",
  CreateCollection = "CreateCollection",
  OrganizeCollection = "OrganizeCollection",
  SyncLibrary = "SyncLibrary",
  ConnectAccount = "ConnectAccount",
  DisconnectAccount = "DisconnectAccount",
  AskQuestion = "AskQuestion",
  Help = "Help",
}
