export enum ClarificationType {
  AMBIGUOUS_GAME = "AMBIGUOUS_GAME",
  AMBIGUOUS_ENTITY = "AMBIGUOUS_ENTITY",
  MISSING_ENTITY = "MISSING_ENTITY",
  MISSING_PARAMETER = "MISSING_PARAMETER",
  MISSING_PERMISSION = "MISSING_PERMISSION",
  CONFIRM_ACTION = "CONFIRM_ACTION",
  CUSTOM = "CUSTOM",
}

