export const ExecutionConstants = {
  STATUS_PENDING: "PENDING",
  STATUS_RUNNING: "RUNNING",
  STATUS_SUCCESS: "SUCCESS",
  STATUS_FAILED: "FAILED",
  STATUS_PARTIAL_SUCCESS: "PARTIAL_SUCCESS",
  STATUS_SKIPPED: "SKIPPED",
  STATUS_CANCELLED: "CANCELLED",

  EVENT_STARTED: "STARTED",
  EVENT_VALIDATED: "VALIDATED",
  EVENT_STEP_STARTED: "STEP_STARTED",
  EVENT_STEP_FINISHED: "STEP_FINISHED",
  EVENT_STEP_FAILED: "STEP_FAILED",
  EVENT_STEP_RETRIED: "STEP_RETRIED",
  EVENT_FINISHED: "FINISHED",
  EVENT_FAILED: "FAILED",
};

export default ExecutionConstants;
